server:
  port: 8380

spring:
  application:
    name: Usuarios

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8800/eureka/
 